# Generated by Django 2.2.1 on 2019-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_id_point', models.CharField(max_length=12, unique=True, verbose_name='RUT de la Empresa')),
                ('name_point', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('address_point', models.CharField(max_length=100, verbose_name='Dirección de la empresa')),
                ('latitude_point', models.FloatField()),
                ('longitude_point', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Punto de reciclaje',
                'verbose_name_plural': 'Puntos de reciclaje',
            },
        ),
        migrations.CreateModel(
            name='RecyclingPointRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_approbation_date', models.DateTimeField(auto_now=True, null=True)),
                ('was_evaluated', models.BooleanField(default=False)),
                ('was_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
