# Generated by Django 2.2.1 on 2019-05-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecopoints', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpointrequest',
            name='request_municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Municipality'),
        ),
        migrations.AddField(
            model_name='recyclingpointrequest',
            name='request_recyclingpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecopoints.RecyclingPoint'),
        ),
        migrations.AddField(
            model_name='recyclingpointrequest',
            name='request_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Person'),
        ),
        migrations.AddField(
            model_name='recyclingpoint',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.City', verbose_name='Comuna en que está situada la empresa'),
        ),
        migrations.AddField(
            model_name='recyclingpoint',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Country', verbose_name='Región en que está situada la empresa'),
        ),
    ]
